In [3]:
# import tensorflow
import tensorflow as tf

# build computational graph
a = tf.placeholder(tf.int16)
b = tf.placeholder(tf.int16)

addition = tf.add(a, b)

# initialize variables
init = tf.global_variables_initializer()

# create session and run the graph
sess=tf.Session()

sess.run(init)
print "Addition: %i" % sess.run(addition, feed_dict={a: 2, b: 3})

# close session
sess.close()

Addition: 5


In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

In [3]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [3]:
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())

In [6]:
sess = tf.Session()
#print(sess.run(total))


In [5]:
print(sess.run({'ab':(a, b), 'total':total}))

{'total': 7.0, 'ab': (3.0, 4.0)}


In [7]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2,vec)))


[ 0.15907478  0.52939129  0.67453039]
[ 0.01339912  0.69998431  0.15515602]
(array([ 1.62584293,  1.08522022,  1.85722613], dtype=float32), array([ 2.62584305,  2.08522034,  2.85722613], dtype=float32), array([ 0.62584293,  0.08522022,  0.85722613], dtype=float32))


In [8]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [9]:
print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

7.5
[ 3.  7.]


In [4]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()


In [7]:
while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break


[0 1]
[2 3]
[4 5]
[6 7]


In [8]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

In [9]:
init = tf.global_variables_initializer()
sess.run(init)

In [10]:
print(sess.run(y, {x: [[1, 2, 3],[4, 5, 6]]}))

[[ 0.67465425]
 [-0.2743485 ]]


In [11]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.layers.dense(x, units=1)

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y, {x: [[1, 2, 3], [4, 5, 6]]}))

[[ 1.15012395]
 [ 2.06746387]]


In [12]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

In [13]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))

(None, None)

In [14]:
print(sess.run(inputs))

[[  1.   0.   5.]
 [  1.   0.  10.]
 [  0.   1.   8.]
 [  0.   1.   9.]]


In [15]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)


In [16]:
linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)


In [17]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y_pred))


[[ 0.76125753]
 [ 1.52251506]
 [ 2.28377247]
 [ 3.04503012]]


In [18]:
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

print(sess.run(loss))

15.4589


In [19]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [30]:
for i in range(10000):
  loss_value = sess.run((train, loss))
  #print(loss_value)

In [31]:
print(sess.run(y_pred))

[[ -7.45058060e-06]
 [ -1.00000346e+00]
 [ -1.99999952e+00]
 [ -2.99999547e+00]]


In [36]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

optimizer = tf.train.GradientDescentOptimizer(.001)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
for i in range(10000):
  _, loss_value = sess.run((train, loss))
  #print(loss_value)

print(sess.run(y_pred))

[[-0.05028325]
 [-1.02436543]
 [-1.99844766]
 [-2.97252989]]


In [2]:
print(tf.__version__)

1.5.0
